apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Dr3amk8ller/flightapp
      sshPrivateKeySecret:
        name: argocd-ssh-secret
        key: sshPrivateKey

