apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
  - name: context
    value: https://github.com/Dr3amk8ller/flightapp.git

